import { SchoolConfig, NewsArticle } from '../types';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: 'smpn1bks',
  identity: {
    name: 'SMP Negeri 1 Bengkalis',
    shortName: 'SMPN 1 Bengkalis',
    tagline: 'Mewujudkan Insan Beriman, Berakhlak Mulia, Cerdas, Terampil, dan Berbudaya Lingkungan',
    npsn: '10495146',
    akreditasi: 'Akreditasi A (Unggul)',
    logoUrl: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?w=160&auto=format&fit=crop&q=80',
    faviconUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=64&auto=format&fit=crop&q=80',
    tickerEnabled: true,
    tickerText: '📢 Selamat Datang di Portal Resmi SMP Negeri 1 Bengkalis | Jl. Pertanian, Bengkalis Kota | NPSN: 10495146 | PPDB & Informasi Prestasi Siswa 🏆',
    primaryColor: 'blue',
  },
  header: {
    heroTitle: 'Selamat Datang di Portal Resmi SMP Negeri 1 Bengkalis',
    heroSubtitle: 'Sekolah Menengah Pertama rujukan terdepan di Kabupaten Bengkalis yang berdedikasi melahirkan generasi berkarakter luhur, berprestasi akademik & non-akademik, serta menguasai sains dan teknologi.',
    heroImageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1600&auto=format&fit=crop&q=80',
    heroCtaText: 'Info PPDB & Pendaftaran',
    heroCtaLink: '#ppdb',
    secondaryCtaText: 'Profil & Prestasi Sekolah',
    secondaryCtaLink: '#profil',
    highlights: [
      { id: '1', icon: 'Award', label: 'Akreditasi Sekolah', value: 'Unggul (A)' },
      { id: '2', icon: 'GraduationCap', label: 'Kelulusan Siswa', value: '100% Lulus' },
      { id: '3', icon: 'Users', label: 'Peserta Didik', value: '850+ Siswa' },
      { id: '4', icon: 'BookOpen', label: 'Pendidik Profesional', value: '55+ Guru' },
    ],
  },
  navMenus: [
    {
      id: 'm1',
      label: 'Beranda',
      path: '#beranda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm2',
      label: 'Profil Sekolah',
      path: '#profil',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd2-1', label: 'Sambutan Kepala Sekolah', path: '#sambutan', description: 'Pesan hangat dari pimpinan SMPN 1 Bengkalis' },
        { id: 'd2-2', label: 'Visi & Misi', path: '#profil-visi', description: 'Arah, cita-cita, dan komitmen mutu pendidikan' },
        { id: 'd2-3', label: 'Fasilitas Belajar', path: '#fasilitas', description: 'Laboratorium IPA, Komputer, & Perpustakaan' },
        { id: 'd2-4', label: 'Video Profil Sekolah', path: '#video-profil', description: 'Tayangan dokumenter aktivitas sekolah' },
      ],
    },
    {
      id: 'm3',
      label: 'Kesiswaan & Ekskul',
      path: '#ekskul',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd3-1', label: 'Ekstrakurikuler', path: '#ekskul', description: 'Pramuka, PMR, Seni Musik Melayu, & Olahraga' },
        { id: 'd3-2', label: 'Prestasi Siswa', path: '#berita', description: 'Koleksi penghargaan tingkat kabupaten & provinsi' },
        { id: 'd3-3', label: 'OSIS SMPN 1', path: '#kesiswaan-osis', description: 'Organisasi Siswa Intra Sekolah' },
      ],
    },
    {
      id: 'm4',
      label: 'Berita & Info',
      path: '#berita',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm5',
      label: 'Agenda Kegiatan',
      path: '#agenda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm6',
      label: 'Lokasi & Kontak',
      path: '#kontak',
      isDropdown: false,
      enabled: true,
    },
  ],
  layoutSections: {
    showHero: true,
    showQuickStats: true,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: true,
    showFacilities: true,
    showExtracurriculars: true,
    showVideoEmbed: true,
    showMapEmbed: true,
  },
  principal: {
    name: 'Drs. H. Syahrul, M.Pd.',
    title: 'Kepala Sekolah SMP Negeri 1 Bengkalis',
    nip: '19680512 199412 1 002',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80',
    quote: 'Mendidik bukan hanya mentransfer ilmu pengetahuan, melainkan menumbuhkan budi pekerti, akhlak mulia, dan kecintaan pada nilai-nilai kearifan lokal serta kemajuan zaman.',
    fullSpeech: `Assalamu’alaikum Warahmatullahi Wabarakatuh, Salam Sejahtera untuk kita semua.\n\nSelamat datang di portal resmi SMP Negeri 1 Bengkalis. Kami mengucapkan terima kasih atas kepercayaan masyarakat Kabupaten Bengkalis yang telah mempercayakan pendidikan putra-putrinya di sekolah kami.\n\nSMP Negeri 1 Bengkalis yang beralamat di Jl. Pertanian, Bengkalis Kota, senantiasa berkomitmen menghadirkan lingkungan belajar yang kondusif, religius, berbudaya, serta berorientasi pada peningkatan mutu akademik dan non-akademik. Melalui implementasi Kurikulum Merdeka dan penguatan Profil Pelajar Pancasila, kami mendidik setiap siswa agar siap menjadi generasi penerus bangsa yang unggul, berintegritas, dan berwawasan lingkungan.\n\nMari bersama-sama bersinergi mewujudkan masa depan anak-anak kita yang gemilang.\n\nWassalamu’alaikum Warahmatullahi Wabarakatuh.`,
  },
  ppdb: {
    enabled: true,
    buttonLabel: 'Info PPDB 2026',
    buttonLink: '#berita',
    openInNewTab: false,
    academicYear: '2026/2027',
    statusText: 'Pendaftaran Dibuka',
    badgeText: 'Tahun Ajaran 2026/2027',
    announcement: 'Penerimaan Peserta Didik Baru (PPDB) SMP Negeri 1 Bengkalis Tahun Ajaran 2026/2027 melalui jalur Zonasi, Afirmasi, Perpindahan Tugas Orang Tua, dan Prestasi.',
    contactPerson: '0812-7561-8899 (Panitia PPDB)',
    brochureUrl: '',
  },
  embeds: {
    youtubeTitle: 'Profil & Tur Lingkungan SMP Negeri 1 Bengkalis',
    youtubeSubtitle: 'Saksikan suasana belajar yang asri, sarana laboratorium, dan keceriaan siswa-siswi kami di Jl. Pertanian, Bengkalis Kota.',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    mapTitle: 'Peta Lokasi SMP Negeri 1 Bengkalis (Jl. Pertanian)',
    mapIframeUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.6656729584407!2d102.1066!3d1.4727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31d161d9a242c759%3A0xb3ef4a65ebae245b!2sBengkalis%2C%20Riau!5e0!3m2!1sid!2sid!4v1625580000000!5m2!1sid!2sid',
  },
  facilities: [
    {
      id: 'f1',
      title: 'Laboratorium IPA Terpadu',
      category: 'Akademik',
      imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
      description: 'Dilengkapi alat peraga Biologi dan Fisika lengkap untuk mendukung praktikum sains dan eksperimen siswa.',
    },
    {
      id: 'f2',
      title: 'Perpustakaan & Pojok Baca Digital',
      category: 'Literasi',
      imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80',
      description: 'Koleksi ribuan buku pelajaran, ensiklopedia, referensi bacaan umum, dan fasilitas komputer literasi digital.',
    },
    {
      id: 'f3',
      title: 'Laboratorium Komputer & Informatika',
      category: 'Teknologi',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
      description: 'Ruang berpendingin udara dengan unit komputer modern untuk pembelajaran TIK, ANBK, dan coding dasar.',
    },
    {
      id: 'f4',
      title: 'Lapangan Olahraga & Seni Terbuka',
      category: 'Olahraga',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
      description: 'Sarana multifungsi untuk upacara bendera, bola voli, basket, futsal, dan kegiatan pentas seni sekolah.',
    },
  ],
  extracurriculars: [
    {
      id: 'e1',
      name: 'Pramuka Gugus Depan Bengkalis',
      category: 'Kepanduan',
      coach: 'Kak Ahmad Zulkarnain, S.Pd.',
      schedule: 'Jumat, 15:00 WIB',
      icon: 'Flag',
      description: 'Pembinaan kedisiplinan, kepemimpinan, keterampilan survival, dan bakti sosial kepanduan.',
    },
    {
      id: 'e2',
      name: 'Sanggar Seni & Musik Melayu',
      category: 'Seni & Budaya',
      coach: 'Nurul Hidayah, S.Sn.',
      schedule: 'Sabtu, 09:00 WIB',
      icon: 'Music',
      description: 'Melestarikan seni tari Melayu, kompang, vokal solo, dan seni musik tradisional khas Bengkalis.',
    },
    {
      id: 'e3',
      name: 'Palang Merah Remaja (PMR)',
      category: 'Kemanusiaan',
      coach: 'Ns. Rina Marlina, S.Kep.',
      schedule: 'Kamis, 15:30 WIB',
      icon: 'HeartHandshake',
      description: 'Pelatihan pertolongan pertama pada kecelakaan (P3K), donor darah, dan kebersihan lingkungan.',
    },
    {
      id: 'e4',
      name: 'Klub Sains & Olimpiade (OSN)',
      category: 'Sains & Riset',
      coach: 'Dedi Kurniawan, M.Pd.',
      schedule: 'Selasa & Kamis, 14:30 WIB',
      icon: 'Cpu',
      description: 'Bimbingan intensif persiapan Olimpiade Sains Nasional bidang Matematika, IPA, dan IPS.',
    },
    {
      id: 'e5',
      name: 'Futsal & Atletik Siswa',
      category: 'Olahraga',
      coach: 'Muhammad Yusuf, S.Pd.',
      schedule: 'Rabu & Sabtu, 16:00 WIB',
      icon: 'Trophy',
      description: 'Latihan fisik, teknik dasar permainan, sportivitas, dan kejuaraan tingkat O2SN Kabupaten Bengkalis.',
    },
    {
      id: 'e6',
      name: 'English Club & Storytelling',
      category: 'Bahasa & Komunikasi',
      coach: 'Siti Aminah, M.Ed.',
      schedule: 'Senin, 15:00 WIB',
      icon: 'MessageSquare',
      description: 'Mengasah kemampuan percakapan bahasa Inggris, pidato (speech), dan lomba bercerita (storytelling).',
    },
  ],
  agendas: [
    {
      id: 'a1',
      title: 'Pekan Asesmen Sumatif Akhir Semester',
      date: '08 - 15 Juni 2026',
      time: '07:30 - 12:00 WIB',
      location: 'Ruang Kelas & Lab Komputer',
      category: 'Akademik',
    },
    {
      id: 'a2',
      title: 'Gelar Karya Projek Profil Pelajar Pancasila (P5)',
      date: '20 Juni 2026',
      time: '08:00 - 14:00 WIB',
      location: 'Aula & Halaman SMPN 1 Bengkalis',
      category: 'Karya Siswa',
    },
    {
      id: 'a3',
      title: 'Sosialisasi Alur Pendaftaran PPDB Zonasi & Prestasi',
      date: '26 Juni 2026',
      time: '09:00 - 11:30 WIB',
      location: 'Aula Utama & Daring via Zoom',
      category: 'Informasi PPDB',
    },
  ],
  footer: {
    aboutText: 'SMP Negeri 1 Bengkalis adalah institusi pendidikan menengah pertama rujukan berakreditasi A di Kabupaten Bengkalis yang berdedikasi mendidik siswa berprestasi, berkarakter mulia, dan berwawasan lingkungan hidup.',
    address: 'Jl. Pertanian, Bengkalis Kota, Kec. Bengkalis, Kab. Bengkalis, Riau 28712',
    phone: '(0766) 21155',
    whatsapp: '+62 812-7654-3210',
    email: 'smpn1bengkalis@gmail.com',
    openingHours: 'Senin - Jumat: 07:00 - 15:30 WIB',
    socialLinks: {
      instagram: 'https://instagram.com/smpn1bengkalis',
      youtube: 'https://youtube.com/@smpn1bengkalis',
      facebook: 'https://facebook.com/smpn1bengkalis',
      twitter: 'https://x.com/smpn1bengkalis',
    },
    copyright: '© 2026 SMP Negeri 1 Bengkalis (NPSN: 10495146). Hak Cipta Dilindungi Undang-Undang.',
  },
  googleAppsScript: {
    enabled: true,
    webAppUrl: '',
    folderId: '',
    spreadsheetId: '',
    autoCreateFolder: true,
    testStatus: 'untested',
  },
};

export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Siswa SMP Negeri 1 Bengkalis Raih Juara 1 Olimpiade Sains & FLS2N Tingkat Kabupaten',
    slug: 'siswa-smpn1-bengkalis-juara-osn-fls2n',
    category: 'Prestasi',
    summary: 'Prestasi membanggakan ditorehkan oleh kontingen siswa SMPN 1 Bengkalis dalam kompetisi sains dan festival seni tingkat Kabupaten Bengkalis.',
    content: `Bengkalis — Civitas akademika SMP Negeri 1 Bengkalis kembali menorehkan prestasi gemilang. Dalam perhelatan Olimpiade Sains Nasional (OSN) dan Festival Lomba Seni Siswa Nasional (FLS2N) tingkat Kabupaten Bengkalis tahun 2026, siswa-siswi SMP Negeri 1 Bengkalis berhasil meraih Juara 1 untuk cabang Matematika, IPA Terpadu, serta Juara 1 Lomba Vokal Solo Lagu Melayu.\n\nKepala Sekolah SMP Negeri 1 Bengkalis menyampaikan apresiasi setinggi-tingginya kepada para pembimbing dan peserta didik yang telah berjuang mengharumkan nama sekolah. Keberhasilan ini merupakan buah dari disiplin bimbingan belajar dan dukungan penuh orang tua siswa.\n\nDokumentasi rangkaian foto penyerahan piala dan sertifikat penghargaan dapat disimak pada galeri di bawah ini.`,
    coverImage: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop&q=80',
    author: 'Humas SMPN 1 Bengkalis',
    date: '03 September 2026',
    isPinned: true,
    views: 1650,
    status: 'published',
    galleryImages: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&auto=format&fit=crop&q=80',
    ],
    actionLink: {
      label: 'Kunjungi Portal Dinas Pendidikan Kab. Bengkalis',
      url: 'https://disdik.bengkaliskab.go.id',
    },
    embedUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embedTitle: 'Video Dokumentasi Penyerahan Piala Prestasi Siswa SMPN 1 Bengkalis',
  },
  {
    id: 'news-2',
    title: 'Informasi Penerimaan Peserta Didik Baru (PPDB) SMP Negeri 1 Bengkalis Tahun Ajaran 2026/2027',
    slug: 'ppdb-smpn1-bengkalis-2026-2027',
    category: 'Pengumuman',
    summary: 'Juknis lengkap pendaftaran siswa baru, jalur zonasi domisili, jalur afirmasi, jalur perpindahan tugas, dan jalur prestasi akademik/non-akademik.',
    content: `Diumumkan kepada seluruh orang tua dan calon peserta didik baru lulusan SD/MI di wilayah Bengkalis dan sekitarnya, bahwa proses Penerimaan Peserta Didik Baru (PPDB) SMP Negeri 1 Bengkalis resmi dibuka.\n\nPendaftaran melayani jalur:\n1. Jalur Zonasi Domisili Wilayah Bengkalis Kota\n2. Jalur Afirmasi bagi keluarga prasejahtera\n3. Jalur Prestasi Akademik & Nilai Rapor / Kejuaraan\n4. Jalur Perpindahan Tugas Orang Tua\n\nSilakan simak alur dan persyaratan berkas melalui pengumuman di bawah atau hubungi sekretariat PPDB di Jl. Pertanian, Bengkalis Kota.`,
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    author: 'Panitia PPDB SMPN 1',
    date: '01 September 2026',
    isPinned: true,
    views: 3120,
    status: 'published',
    actionLink: {
      label: 'Buka Info Resmi PPDB Dinas Pendidikan Bengkalis',
      url: 'https://disdik.bengkaliskab.go.id',
    },
  },
  {
    id: 'news-3',
    title: 'Semarak Peringatan Hari Pendidikan dan Gelar Seni Budaya Melayu di SMPN 1 Bengkalis',
    slug: 'gelar-seni-budaya-melayu-smpn1-bengkalis',
    category: 'Kegiatan',
    summary: 'Mengenalkan kearifan lokal, sastra gurindam, tari persembahan, dan baju adat tradisional Melayu Riau kepada generasi muda.',
    content: `Dalam rangka menanamkan rasa cinta tanah air dan kearifan lokal Melayu Riau, SMP Negeri 1 Bengkalis menggelar pentas seni dan pekan sastra budaya. Seluruh warga sekolah mengenakan busana adat Melayu dan menampilkan aneka atraksi tari persembahan, berbalas pantun, serta pertunjukan musik kompang.\n\nKegiatan ini sekaligus menjadi bagian dari aksi nyata Projek Penguatan Profil Pelajar Pancasila (P5) dengan tema Kearifan Lokal dan Kebhinekaan Global.`,
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    author: 'Tim Kesiswaan',
    date: '28 Agustus 2026',
    isPinned: false,
    views: 940,
    status: 'published',
  },
  {
    id: 'news-4',
    title: 'Aksi Bakti Lingkungan Pramuka SMP Negeri 1 Bengkalis Peduli Kebersihan Pesisir & Sekolah Asri',
    slug: 'pramuka-smpn1-bengkalis-bakti-lingkungan',
    category: 'Ekstrakurikuler',
    summary: 'Anggota Pramuka Gudep SMP Negeri 1 Bengkalis melaksanakan aksi bersih lingkungan dan penanaman pohon penghijauan.',
    content: `Puluhan anggota Pramuka Gugus Depan SMP Negeri 1 Bengkalis antusias mengikuti program bakti lingkungan 'Sekolah Asri & Pesisir Lestari'. Kegiatan difokuskan pada pemilahan sampah organik dan anorganik, pembuatan kompos sekolah, serta penanaman bibit pohon peneduh di area Jl. Pertanian Bengkalis.\n\nPembina Pramuka menyatakan kegiatan ini bertujuan mendidik karakter kepedulian lingkungan sejak dini agar tercipta sekolah yang hijau, nyaman, dan sehat.`,
    coverImage: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    author: 'Gudep Pramuka SMPN 1',
    date: '22 Agustus 2026',
    isPinned: false,
    views: 780,
    status: 'published',
  },
];
