import { SchoolConfig, NewsArticle } from '../types';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: 'smpn1bks',
  identity: {
    name: 'SMA Negeri 1 Nusantara',
    tagline: 'Mewujudkan Generasi Unggul Berkarakter, Berprestasi, dan Berwawasan Global',
    npsn: '20108392',
    akreditasi: 'Akreditasi A (Unggul)',
    logoUrl: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?w=160&auto=format&fit=crop&q=80',
    faviconUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=64&auto=format&fit=crop&q=80',
    tickerEnabled: true,
    tickerText: '📢 Pengumuman: Pendaftaran Peserta Didik Baru (PPDB) Jalur Prestasi & Zonasi Tahun Ajaran 2026/2027 telah dibuka! | Selamat kepada Tim Robotik SMAN 1 Nusantara meraih Juara 1 Tingkat Nasional 🏆',
    primaryColor: 'blue',
  },
  header: {
    heroTitle: 'Selamat Datang di Portal Resmi SMA Negeri 1 Nusantara',
    heroSubtitle: 'Pusat keunggulan pendidikan terdepan yang memadukan penguatan karakter luhur, sains teknologi mutakhir, serta prestasi akademik dan non-akademik berstandar global.',
    heroImageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1600&auto=format&fit=crop&q=80',
    heroCtaText: 'Info PPDB 2026/2027',
    heroCtaLink: '#ppdb',
    secondaryCtaText: 'Jelajahi Profil & Ekskul',
    secondaryCtaLink: '#profil',
    highlights: [
      { id: '1', icon: 'Award', label: 'Akreditasi Sekolah', value: 'Unggul (A+)' },
      { id: '2', icon: 'GraduationCap', label: 'Tembus PTN Favorit', value: '94.8%' },
      { id: '3', icon: 'Users', label: 'Siswa Berprestasi', value: '1,250+' },
      { id: '4', icon: 'BookOpen', label: 'Pendidik Tersertifikasi', value: '85+ Guru' },
    ],
  },
  navMenus: [
    {
      id: 'm1',
      label: 'Beranda',
      path: '#beranda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm2',
      label: 'Profil Sekolah',
      path: '#profil',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd2-1', label: 'Sambutan Kepala Sekolah', path: '#sambutan', description: 'Pesan hangat dari pimpinan sekolah' },
        { id: 'd2-2', label: 'Visi & Misi', path: '#profil-visi', description: 'Arah dan komitmen pendidikan' },
        { id: 'd2-3', label: 'Fasilitas Kampus', path: '#fasilitas', description: 'Laboratorium, perpustakaan, & sarana' },
        { id: 'd2-4', label: 'Video Profil Sekolah', path: '#video-profil', description: 'Tayangan dokumenter lingkungan sekolah' },
      ],
    },
    {
      id: 'm3',
      label: 'Kesiswaan & Ekskul',
      path: '#ekskul',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd3-1', label: 'Ekstrakurikuler Unggulan', path: '#ekskul', description: 'Robotik, Pramuka, PMR, Seni & Futsal' },
        { id: 'd3-2', label: 'Prestasi Siswa', path: '#berita', description: 'Koleksi piala dan medali tingkat nasional' },
        { id: 'd3-3', label: 'OSIS & MPK', path: '#kesiswaan-osis', description: 'Wadah kepemimpinan siswa Nusantara' },
      ],
    },
    {
      id: 'm4',
      label: 'Berita & Artikel',
      path: '#berita',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm5',
      label: 'Agenda Kegiatan',
      path: '#agenda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm6',
      label: 'Lokasi & Kontak',
      path: '#kontak',
      isDropdown: false,
      enabled: true,
    },
  ],
  layoutSections: {
    showHero: true,
    showQuickStats: true,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: true,
    showFacilities: true,
    showExtracurriculars: true,
    showVideoEmbed: true,
    showMapEmbed: true,
  },
  principal: {
    name: 'Drs. H. Bambang Suryanto, M.Pd.',
    title: 'Kepala Sekolah SMA Negeri 1 Nusantara',
    nip: '19710815 199702 1 003',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80',
    quote: 'Pendidikan bukan sekadar mengisi wadah dengan ilmu pengetahuan, melainkan menyalakan api rasa ingin tahu, budi pekerti luhur, dan integritas kepemimpinan.',
    fullSpeech: `Assalamu’alaikum Warahmatullahi Wabarakatuh, Salam Sejahtera untuk kita semua.\n\nSelamat datang di portal resmi SMA Negeri 1 Nusantara. Sebagai lembaga pendidikan yang berdedikasi tinggi terhadap pembentukan insan cendekia, kami berkomitmen untuk terus berinovasi dalam memberikan layanan pendidikan bermutu tinggi.\n\nDi era disrupsi digital ini, anak-anak didik kami tidak hanya dibekali keunggulan sains dan teknologi, namun juga ditekankan pada penguatan karakter profil pelajar Pancasila: beriman, berakhlak mulia, mandiri, bergotong royong, bernalar kritis, dan kreatif.\n\nDengan dukungan tenaga pendidik berdedikasi, sarana prasarana modern, serta sinergi yang harmonis bersama komite dan orang tua siswa, SMA Negeri 1 Nusantara siap mengantarkan generasi muda menggapai cita-cita setinggi langit.\n\nWassalamu’alaikum Warahmatullahi Wabarakatuh.`,
  },
  embeds: {
    youtubeTitle: 'Profil & Tur Virtual Kampus SMAN 1 Nusantara',
    youtubeSubtitle: 'Saksikan suasana belajar interaktif, fasilitas modern laboratorium sains, dan kegiatan siswa di kampus hijau kami.',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    mapTitle: 'Lokasi Kampus SMAN 1 Nusantara',
    mapIframeUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126920.28588899806!2d106.759478!3d-6.229728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f3e945e34b9d%3A0x5371bf0fdad786a2!2sJakarta%2C%20Indonesia!5e0!3m2!1sid!2sid!4v1625580000000!5m2!1sid!2sid',
  },
  facilities: [
    {
      id: 'f1',
      title: 'Laboratorium Sains Terpadu',
      category: 'Akademik',
      imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
      description: 'Dilengkapi mikroskop digital, fume hood berstandar riset, dan reagen kimia lengkap untuk praktikum Fisika, Kimia, dan Biologi.',
    },
    {
      id: 'f2',
      title: 'Perpustakaan Digital & Corner Multimedia',
      category: 'Literasi',
      imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80',
      description: 'Koleksi 15.000+ buku fisik dan e-book langganan internasional dengan ruang baca ber-AC yang tenang dan nyaman.',
    },
    {
      id: 'f3',
      title: 'Laboratorium Komputer & AI Coding',
      category: 'Teknologi',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
      description: 'Unit komputer spesifikasi tinggi terkoneksi internet Gigabit untuk pembelajaran informatika, desain grafis, dan robotika.',
    },
    {
      id: 'f4',
      title: 'Gedung Olahraga & Lapangan Futsal',
      category: 'Olahraga',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
      description: 'Gelanggang indoor serbaguna untuk bola basket, voli, bulutangkis, dan lapangan outdoor berstandar pertandingan nasional.',
    },
  ],
  extracurriculars: [
    {
      id: 'e1',
      name: 'Tim Robotik & IoT Nusantara',
      category: 'Sains & Teknologi',
      coach: 'Ir. Hendra Wijaya, M.T.',
      schedule: 'Selasa & Kamis, 15:30 WIB',
      icon: 'Cpu',
      description: 'Pengembangan mikrokontroler Arduino, sensorik cerdas, mekanik otomasi, dan persiapan kompetisi WRO.',
    },
    {
      id: 'e2',
      name: 'Paskibraka Satya Negara',
      category: 'Kepemimpinan',
      coach: 'Sersan Mayor Danu W.',
      schedule: 'Rabu & Sabtu, 15:00 WIB',
      icon: 'Flag',
      description: 'Kedisiplinan baris-berbaris, formasi pengibaran bendera pusaka, kepemimpinan, dan ketahanan fisik prima.',
    },
    {
      id: 'e3',
      name: 'Paduan Suara & Orkestra Harmoni',
      category: 'Seni & Budaya',
      coach: 'Maria Anggraini, S.Sn.',
      schedule: 'Senin & Jumat, 15:30 WIB',
      icon: 'Music',
      description: 'Olah vokal, paduan suara aransemen nusantara & klasik, serta ensambel alat musik akustik dan modern.',
    },
    {
      id: 'e4',
      name: 'Palang Merah Remaja (PMR)',
      category: 'Kemanusiaan',
      coach: 'dr. Siti Rahmawati',
      schedule: 'Kamis, 15:30 WIB',
      icon: 'HeartHandshake',
      description: 'Pertolongan pertama pada kecelakaan (P3K), kesiapsiagaan bencana alam, donor darah, dan bakti sosial.',
    },
    {
      id: 'e5',
      name: 'Klub Bahasa Inggris (English Club & Debate)',
      category: 'Bahasa & Komunikasi',
      coach: 'Sarah Johnson, M.Ed.',
      schedule: 'Rabu, 15:30 WIB',
      icon: 'MessageSquare',
      description: 'Melatih public speaking, model united nations (MUN), persiapan TOEFL/IELTS, dan lomba debat parlementer.',
    },
    {
      id: 'e6',
      name: 'Akademi Futsal & Sepakbola',
      category: 'Olahraga',
      coach: 'Coach Ricky Subagja',
      schedule: 'Selasa & Jumat, 16:00 WIB',
      icon: 'Trophy',
      description: 'Teknik dasar taktik pertandingan, ketahanan stamina, dan kejuaraan antar SMA se-provinsi.',
    },
  ],
  agendas: [
    {
      id: 'a1',
      title: 'Pekan Penilaian Akhir Semester (PAS) Genap',
      date: '15 - 22 Juni 2026',
      time: '07:30 - 12:30 WIB',
      location: 'Ruang Ujian Berbasis Komputer (CBT)',
      category: 'Akademik',
    },
    {
      id: 'a2',
      title: 'Sosialisasi Seleksi Nasional Masuk PTN (SNBP & SNBT)',
      date: '28 Juni 2026',
      time: '09:00 - 12:00 WIB',
      location: 'Aula Utama & Zoom Webinar Orang Tua',
      category: 'Karier & Kuliah',
    },
    {
      id: 'a3',
      title: 'Gelar Karya Projek Penguatan Profil Pelajar Pancasila (P5)',
      date: '04 Juli 2026',
      time: '08:00 - 15:00 WIB',
      location: 'Plaza Seni & Lapangan Indoor',
      category: 'Karya Siswa',
    },
  ],
  footer: {
    aboutText: 'SMA Negeri 1 Nusantara adalah institusi pendidikan menengah atas unggulan berakreditasi A yang berorientasi pada pencapaian akademik berstandar internasional serta integritas karakter moral kebangsaan.',
    address: 'Jl. Pendidikan No. 45, Kompleks Kampus Hijau, Nusantara 12345',
    phone: '(021) 7890-1234',
    whatsapp: '+62 812-3456-7890',
    email: 'info@sman1nusantara.sch.id',
    openingHours: 'Senin - Jumat: 07:00 - 16:00 WIB',
    socialLinks: {
      instagram: 'https://instagram.com/sman1nusantara',
      youtube: 'https://youtube.com/@sman1nusantara',
      facebook: 'https://facebook.com/sman1nusantara',
      twitter: 'https://x.com/sman1nusantara',
    },
    copyright: '© 2026 SMA Negeri 1 Nusantara. Hak Cipta Dilindungi Undang-Undang.',
  },
};

export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Tim Robotik SMAN 1 Nusantara Raih Medali Emas National Robotics Olympiad 2026',
    slug: 'tim-robotik-raih-emas-nro-2026',
    category: 'Prestasi',
    summary: 'Karya robot pembersih sampah perairan otomatis berbasis IoT buatan siswa kelas XI sukses memukau dewan juri di Jakarta Convention Center.',
    content: `Jakarta — Prestasi membanggakan kembali diukir oleh peserta didik SMA Negeri 1 Nusantara. Tim Robotik yang digawangi oleh Muhammad Alif (Kelas XI MIPA 1) dan Nayla Zahra (Kelas XI MIPA 3) berhasil membawa pulang medali emas dalam ajang bergengsi National Robotics Olympiad (NRO) 2026.\n\nDalam kompetisi yang diikuti oleh lebih dari 120 sekolah unggulan se-Indonesia tersebut, tim memamerkan inovasi berupa prototype robot amfibi berkamera AI yang sanggup mendeteksi serta mengumpulkan mikroplastik dan sampah terapung secara efisien.\n\nDokumentasi rangkaian foto pengujian lapangan dan penyerahan piala dapat dilihat pada galeri foto di bawah ini. Anda juga dapat mengunjungi portal resmi kompetisi robotik nasional melalui tautan berikut: [Laman Resmi National Robotics Olympiad](https://pusatprestasinasional.kemdikbud.go.id).`,
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    author: 'Humas SMAN 1 Nusantara',
    date: '02 September 2026',
    isPinned: true,
    views: 1420,
    status: 'published',
    galleryImages: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop&q=80',
    ],
    actionLink: {
      label: 'Kunjungi Portal Pusat Prestasi Nasional Kemdikbud',
      url: 'https://pusatprestasinasional.kemdikbud.go.id',
    },
    embedUrl: 'https://www.youtube.com/watch?v=kYcT_Q8rE8g',
    embedTitle: 'Video Demonstrasi Pengujian Robot Amfibi AI di Danau Kampus',
  },
  {
    id: 'news-2',
    title: 'Pembukaan Pendaftaran Peserta Didik Baru (PPDB) & Aplikasi Verifikasi Berkas Online',
    slug: 'pembukaan-ppdb-2026-2027',
    category: 'Pengumuman',
    summary: 'Informasi alur, jadwal verifikasi berkas, kuota zonasi, jalur afirmasi, dan aplikasi formulir pendaftaran interaktif berbasis web.',
    content: `Diumumkan kepada seluruh calon wali murid dan peserta didik baru lulusan SMP/MTs sederajat, bahwa proses Penerimaan Peserta Didik Baru (PPDB) SMA Negeri 1 Nusantara resmi dibuka mulai tanggal 10 September hingga 25 September 2026.\n\nJalur yang tersedia meliputi:\n1. Jalur Prestasi Akademik & Nilai Rapor (30%)\n2. Jalur Zonasi Domisili (50%)\n3. Jalur Afirmasi Keluarga Ekonomi Tidak Mampu (15%)\n4. Jalur Perpindahan Tugas Orang Tua (5%)\n\nCalon siswa dapat langsung mengisi formulir interaktif di bawah ini atau membuka formulir di tab baru untuk tampilan yang lebih leluasa dan layar penuh. Anda juga dapat mengunduh panduan lengkap juknis PPDB melalui tombol tautan khusus.`,
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    author: 'Panitia PPDB 2026',
    date: '01 September 2026',
    isPinned: true,
    views: 2850,
    status: 'published',
    actionLink: {
      label: 'Unduh Petunjuk Teknis (Juknis) PPDB 2026/2027 PDF',
      url: 'https://kemdikbud.go.id',
    },
    embedUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSc_ExamplePPDB/viewform',
    embedTitle: 'Formulir Pendaftaran & Validasi Data Siswa Baru (Interaktif)',
  },
  {
    id: 'news-3',
    title: 'Studi Tiruan Budaya dan Kunjungan Industri Siswa Kelas XII ke Kampus Riset Nasional',
    slug: 'kunjungan-industri-kelas-xii-2026',
    category: 'Kegiatan',
    summary: 'Memperluas wawasan karir dan teknologi mutakhir sebelum memasuki gerbang perguruan tinggi dan dunia profesional.',
    content: `Sebanyak 320 siswa kelas XII mengikuti kegiatan edukatif kunjungan kampus dan pusat penelitian nanoteknologi. Kegiatan ini bertujuan memberikan gambaran riil mengenai prospek riset masa depan, iklim perkuliahan, dan pengenalan laboratorium berstandar industri 4.0.\n\nPara siswa mendapatkan kesempatan langsung berdiskusi dengan peneliti senior tentang kecerdasan buatan, energi terbarukan, dan rekayasa genetika. Rangkaian momen dokumentasi kunjungan industri dapat disimak melalui album galeri foto di bawah.`,
    coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    author: 'Koordinator Kesiswaan',
    date: '28 Agustus 2026',
    isPinned: false,
    views: 890,
    status: 'published',
    galleryImages: [
      'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=800&auto=format&fit=crop&q=80',
    ],
  },
  {
    id: 'news-4',
    title: 'Koleksi Medali Paduan Suara Nusantara Choir di Festival Seni Musik Internasional',
    slug: 'paduan-suara-nusantara-juara-internasional',
    category: 'Ekstrakurikuler',
    summary: 'Membawakan lagu daerah dengan balutan aransemen kontemporer, tim paduan suara meraih Silver Diploma di Bali International Choir.',
    content: `Tim Nusantara Choir membuktikan bahwa dedikasi latihan intensif membuahkan hasil manis. Berkompetisi di hadapan dewan juri mancanegara, anak-anak SMA Negeri 1 Nusantara menyuguhkan perpaduan vokal yang harmonis dan koreografi teatrikal nusantara yang memukau.\n\nPembina ekstrakurikuler seni suara mengungkapkan rasa harunya atas disiplin tinggi para siswa selama berbulan-bulan latihan sepulang jam sekolah. Trofi ini dipersembahkan untuk seluruh civitas akademika dan almamater tercinta.`,
    coverImage: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
    author: 'Tim Jurnalistik Siswa',
    date: '20 Agustus 2026',
    isPinned: false,
    views: 760,
    status: 'published',
  },
];
